
Trajectory_node:
  ros__parameters:
    area: 4.0
    coordenadas_x: [0.0,    1.5,    1.5,    0.0,    0.0]
    coordenadas_y: [0.0,    0.0,    1.5,    1.5,    0.0]
    velocidad:     [0.35,    0.35,    0.35,    0.35,    0.35]

control_node:
  ros__parameters:
    kp_lin: 1.5
    ki_lin: 0.5
    kd_lin: 0.7

    kp_ang: 1.75
    ki_ang: 0.6
    kd_ang: 1.0

    dist_tolerance: 0.08
    ang_tolerance:  0.315
    max_linear:     0.15
    max_angular:    0.8
    control_rate:   20.0
